# Generated by Django 2.0.7 on 2018-07-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('code', models.CharField(blank=True, default='', max_length=200)),
                ('memo', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
