# Generated by Django 2.0.7 on 2018-07-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20180709_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='created',
        ),
        migrations.RemoveField(
            model_name='info',
            name='release_data',
        ),
    ]
