# Generated by Django 2.0.7 on 2018-07-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20180709_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='code',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='info',
            name='memo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
